### ISSUE TITLE
Cannot set/save Keyboard Shortcuts

### ISSUE THREAD

**Issue by Jeansen** [negesti/gnome-shell-extensions-negesti#163]
## Expected Behavior
Setting a keyboard shortcut for any enabled actions should save the given shortcut so it can from then on be used to e.g. move around windows.

## Current Behavior
When assigning a keyboard shortcut to an action, e.g. "Move to top", the modal window with the current settings displayed simply disappears. I can open the settings again, and try to apply any kind of shortcut but every time the Window is simply closed again and no settings have been saved.

## Possible Solution
None, so far. I could not find anything in the logs ...

## Steps to Reproduce (for bugs)
1. Open gnome-tweaks (Alt-F2 and type: gnome-tweaks)
2. Navigate to "Extensions"
3. Open the settings for "Put windows".
4. Navigate to "Keyboard Shortcus"
5. Double-click the modifier of any enabled action. It should now show "New accelerator ..."
6. Try any keyboard combination.

## Context
I simply wanted to change an existing accelrator and add a new one for an action I haven't used so far.

## Your Environment
GNOME Shell 3.30.2

Debian GNU/Linux bullseye/sid

**Comment by negesti** [comment]
Just tried, and it work with fedora 30 /gnome-shell 3.23.2 
Any hints if you rund ``` gnome-tweaks -d``` from console?

**Comment by TheBlackKoala** [comment]
I have the same problem and it seems to be the exact same thing as is happening in #129.
Arch/GNOME Shell 3.32.2/Xorg

The last error i get before the settings screen crashes is 

> putWindow@clemens.lab21.org/prefs.js 7]: Requiring Wnck but it has 2 versions available; use imports.gi.versions to pick one

but that happens even before i input the shortcut.

all the output that seemed relevant to putWindows was:

> DEBUG   : Query URL: https://extensions.gnome.org/extension-info/?uuid=putWindow@clemens.lab21.org
> INFO    : e.g.o no updates for putWindow@clemens.lab21.org (shell version 3.32.2 extension version 26.0)
> Gjs-Message: 01:24:51.920: JS WARNING: [/home/tor/.local/share/gnome-shell/extensions/putWindow@clemens.lab21.org/prefs.js 7]: Requiring Wnck but it has 2 versions available; use imports.gi.versions to pick one

This is the output relevant to putwindow in journalctl:

> Aug 20 01:16:33 Datamat gnome-shell-ext[31066]: JS WARNING: [/home/tor/.local/share/gnome-shell/extensions/putWindow@clemens.lab21.org/prefs.js 7]: Requiring Wnck but it has 2 versions available; use imports.gi.versions to pick one
> Aug 20 01:11:45 Datamat gnome-shell-ext[30089]: JS LOG: Extension putWindow@clemens.lab21.org already installed in /home/tor/.local/share/gnome-shell/extensions/putWindow@clemens.lab21.org. /home/tor/.local/share/gnome-shell/extensions/putWindow@clemens.lab21.org will not be loaded

**Comment by Jeansen** [comment]
Running `gnome-tweaks -d` I see the following when in step 5 above (clicking the modifier)

`(gnome-shell-extension-prefs:32650): Gdk-CRITICAL **: 22:04:13.276: gdk_window_get_window_type: assertion 'GDK_IS_WINDOW (window)' failed
`
When I then enter something, the window just disappears, no further output on the terminal.

**Comment by Jeansen** [comment]
Oh, yes. And I am also on Xorg, not Waylang!

**Comment by negesti** [comment]
As I'm not able to reproduce the problem fixing this is not really easy. 
Basically the pref.js uses _createBindingList#389 to create a table for all keybinding. 

Have you tried to set a keybinding for "Move Focus". It uses the createBindingList too to create the list. But maybe it's just a problem with settings object .

**Comment by negesti** [comment]
@TheBlackKoala as you get the wnck error, can you please try to add "imports.gi.versions.Gtk = '3.0';" as the first line inside prefs.js?

**Comment by TheBlackKoala** [comment]
@negesti i think you mean `imports.gi.versions.Wnck = '3.0';` - that removes the error but not the shortcut problem

**Comment by TheBlackKoala** [comment]
@negesti  in #129 you mention a workaround using dconf.
This is all i see in dconf-editor for the settings:
![Screenshot from 2019-08-26 22-55-09](https://user-images.githubusercontent.com/8694231/63723038-ccc85580-c854-11e9-9347-67855a14a61b.png)

**Comment by Jeansen** [comment]
@negesti You could take the live CD from Debian stable and boot a VM with it. Install your extension and try the steps above. This way I was able to produce the problem, too.

https://cdimage.debian.org/debian-cd/current-live/amd64/iso-hybrid/

**Comment by negesti** [comment]
@TheBlackKoala Dconf only contains properties that have been changed. The default values are loaded from ``schemas/org.gnome.shell.extensions.org-lab21-putwindow.gschema.xml``.
This file may be a temporary workaround. You can change the values there, run ``make`` in the schemas folder and reload the shell. This should change the default settings

@Jeansen 
I just started the Live CD and "install" the extension. aka i downloaded version 26 (the last v3.30 version) and can change the settings without problems :(

Which version do you use? 
``cat ~/.local/share/gnome-shell/extensions/putWindow@clemens.lab21.org/metadata.json``

**Comment by TheBlackKoala** [comment]
@negesti i can change what it says the shortcut is but i still don't get any result of the shortcut.

**Comment by negesti** [comment]
> .. don't get any result of the shorcut
aka. you can not move your windows?

btw. the preferences can be started directly using ``gnome-shell-extension-prefs putWindow@clemens.lab21.org``

**Comment by Jeansen** [comment]
@negesti Let me check, I'll get back here soon.

**Comment by Jeansen** [comment]
Sorry, took a while. Well, it is interesting. I tested it on my laptop and there I have the same version of Gnome. At least gnome-shell is the same version and also the other settings are very similar. Just cloned it from my current system about half a year ago. The only difference is that on my current machine I now run Debian unstable (for some time) and on my laptop it is still Debian test. So I believe something deeper in Gnome must be the cause, maybe gvfs? I tried also disabling all other extensions including user themes ... but without success.

I'd like to provide more details but am (yet) unable to get more debugging details. The only other thing that pops into my mind for testing now is installing a clean stable system (where everything works) and then bump it to unstable and see what happens.....

**Comment by Jeansen** [comment]
I will do that now and share my results later today ..... it's weekend ;-)

**Comment by Jeansen** [comment]
Mhm..ok. Then it seems something on my system is broken. Now I installed a fresh and new virtual system, upgraded it to unstable and can still change the settings. I'll investigate further, but I do now believe it is not an issue with this extension but somewhere in my system.

**Comment by negesti** [comment]
Any log details if you start the prefs tools from cmd line directly?
 ```gnome-shell-extension-prefs putWindow@clemens.lab21.org```

**Comment by Jeansen** [comment]
After I run the command `gnome-shell-extension-prefs putWindow@clemens.lab21.org`

```
Gjs-Message: 12:38:01.081: JS LOG: Extension alternate-tab@gnome-shell-extensions.gcampax.github.com already installed in /home/marcel/.local/share/gnome-shell/extensions/alternate-tab@gnome-shell-extensions.gcampax.github.com. /usr/share/gnome-shell/extensions/alternate-tab@gnome-shell-extensions.gcampax.github.com will not be loaded
Gjs-Message: 12:38:01.081: JS LOG: Extension apps-menu@gnome-shell-extensions.gcampax.github.com already installed in /home/marcel/.local/share/gnome-shell/extensions/apps-menu@gnome-shell-extensions.gcampax.github.com. /usr/share/gnome-shell/extensions/apps-menu@gnome-shell-extensions.gcampax.github.com will not be loaded
Gjs-Message: 12:38:01.081: JS LOG: Extension auto-move-windows@gnome-shell-extensions.gcampax.github.com already installed in /home/marcel/.local/share/gnome-shell/extensions/auto-move-windows@gnome-shell-extensions.gcampax.github.com. /usr/share/gnome-shell/extensions/auto-move-windows@gnome-shell-extensions.gcampax.github.com will not be loaded
Gjs-Message: 12:38:01.081: JS LOG: Extension drive-menu@gnome-shell-extensions.gcampax.github.com already installed in /home/marcel/.local/share/gnome-shell/extensions/drive-menu@gnome-shell-extensions.gcampax.github.com. /usr/share/gnome-shell/extensions/drive-menu@gnome-shell-extensions.gcampax.github.com will not be loaded
Gjs-Message: 12:38:01.082: JS LOG: Extension launch-new-instance@gnome-shell-extensions.gcampax.github.com already installed in /home/marcel/.local/share/gnome-shell/extensions/launch-new-instance@gnome-shell-extensions.gcampax.github.com. /usr/share/gnome-shell/extensions/launch-new-instance@gnome-shell-extensions.gcampax.github.com will not be loaded
Gjs-Message: 12:38:01.082: JS LOG: Extension mailnag@pulb.github.com already installed in /home/marcel/.local/share/gnome-shell/extensions/mailnag@pulb.github.com. /usr/share/gnome-shell/extensions/mailnag@pulb.github.com will not be loaded
Gjs-Message: 12:38:01.082: JS LOG: Extension native-window-placement@gnome-shell-extensions.gcampax.github.com already installed in /home/marcel/.local/share/gnome-shell/extensions/native-window-placement@gnome-shell-extensions.gcampax.github.com. /usr/share/gnome-shell/extensions/native-window-placement@gnome-shell-extensions.gcampax.github.com will not be loaded
Gjs-Message: 12:38:01.084: JS LOG: Extension places-menu@gnome-shell-extensions.gcampax.github.com already installed in /home/marcel/.local/share/gnome-shell/extensions/places-menu@gnome-shell-extensions.gcampax.github.com. /usr/share/gnome-shell/extensions/places-menu@gnome-shell-extensions.gcampax.github.com will not be loaded
Gjs-Message: 12:38:01.084: JS LOG: Extension screenshot-window-sizer@gnome-shell-extensions.gcampax.github.com already installed in /home/marcel/.local/share/gnome-shell/extensions/screenshot-window-sizer@gnome-shell-extensions.gcampax.github.com. /usr/share/gnome-shell/extensions/screenshot-window-sizer@gnome-shell-extensions.gcampax.github.com will not be loaded
Gjs-Message: 12:38:01.085: JS LOG: Extension user-theme@gnome-shell-extensions.gcampax.github.com already installed in /home/marcel/.local/share/gnome-shell/extensions/user-theme@gnome-shell-extensions.gcampax.github.com. /usr/share/gnome-shell/extensions/user-theme@gnome-shell-extensions.gcampax.github.com will not be loaded
Gjs-Message: 12:38:01.086: JS LOG: Extension window-list@gnome-shell-extensions.gcampax.github.com already installed in /home/marcel/.local/share/gnome-shell/extensions/window-list@gnome-shell-extensions.gcampax.github.com. /usr/share/gnome-shell/extensions/window-list@gnome-shell-extensions.gcampax.github.com will not be loaded
Gjs-Message: 12:38:01.086: JS LOG: Extension windowsNavigator@gnome-shell-extensions.gcampax.github.com already installed in /home/marcel/.local/share/gnome-shell/extensions/windowsNavigator@gnome-shell-extensions.gcampax.github.com. /usr/share/gnome-shell/extensions/windowsNavigator@gnome-shell-extensions.gcampax.github.com will not be loaded
Gjs-Message: 12:38:01.086: JS LOG: Extension workspace-indicator@gnome-shell-extensions.gcampax.github.com already installed in /home/marcel/.local/share/gnome-shell/extensions/workspace-indicator@gnome-shell-extensions.gcampax.github.com. /usr/share/gnome-shell/extensions/workspace-indicator@gnome-shell-extensions.gcampax.github.com will not be loaded
```
Then I select the keyboards shortcut entry and after double clicking one entry for change this line is added:
`gnome-shell-extension-prefs:3685): Gdk-CRITICAL **: 12:38:07.544: gdk_window_get_window_type: assertion 'GDK_IS_WINDOW (window)' failed
`
And when I then issue a shortcut I get  `Segmentation fault`

**Comment by Jeansen** [comment]
Oh, today I updated via the gnome extensions website to version 27. When I now just want to open the settings, I get:

```
TypeError: extensionUtils.getSettings is not a function

Stack trace:
  loadSettings@/home/marcel/.local/share/gnome-shell/extensions/putWindow@clemens.lab21.org/utils.js:81:28
  _init@/home/marcel/.local/share/gnome-shell/extensions/putWindow@clemens.lab21.org/utils.js:53:5
  Utils@/home/marcel/.local/share/gnome-shell/extensions/putWindow@clemens.lab21.org/utils.js:7:3
  @/home/marcel/.local/share/gnome-shell/extensions/putWindow@clemens.lab21.org/prefs.js:14:15
  _getExtensionPrefsModule@resource:///org/gnome/shell/extensionPrefs/main.js:67:13
  wrapper@resource:///org/gnome/gjs/modules/_legacy.js:82:22
  _selectExtension@resource:///org/gnome/shell/extensionPrefs/main.js:82:31
  wrapper@resource:///org/gnome/gjs/modules/_legacy.js:82:22
  _onCommandLine@resource:///org/gnome/shell/extensionPrefs/main.js:235:17
  wrapper@resource:///org/gnome/gjs/modules/_legacy.js:82:22
  main@resource:///org/gnome/shell/extensionPrefs/main.js:389:5
  @<main>:1:43
```

**Comment by negesti** [comment]
The ``getSettings`` problem is fixed by #166 #167

**Comment by Jeansen** [comment]
So, the getSettings problem is gone, but the other problem persists. I've remove the extensions, installed it again (di a logout and login in-between to flush dconf settings), I also tried the master branch. But still, as soon as I want to set a shortcut, I get this segement fault. But I will not falter ;-) I still have some things I want to try.

**Comment by Jeansen** [comment]
Here's an update of gnome shell version 3.38.1 I can try to update a shortcut, but the field then switches back to disabled. So, the segment fault is gone, but anyway, I cannot set a new shortcut.

Here's what I cant when running `journalctl /usr/bin/gnome-shell -f`

```
ov 06 21:28:13 omph-laptop gnome-shell[5353]: Can't update stage views actor StWidget is on because it needs an allocation.
Nov 06 21:29:35 omph-laptop gnome-shell[5353]: Can't update stage views actor StWidget is on because it needs an allocation.
Nov 06 21:30:35 omph-laptop gnome-shell[5353]: Window manager warning: Buggy client sent a _NET_ACTIVE_WINDOW message with a timestamp of 0 for 0x3e0000c
Nov 06 21:31:18 omph-laptop gnome-shell[5353]: ERROR: Error getting parameter! Can not get config by name locations.Org.gnome.Shell.Extensions defaulting to false'value is undefined
Nov 06 21:31:18 omph-laptop gnome-shell[5353]: Can't update stage views actor StWidget is on because it needs an allocation.
```
